apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: playlistplayoffs-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: playlistplayoffs.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web
            port:
              number: 3000
  tls:
  - hosts:
    - playlistplayoffs.com
    secretName: tls-secret
