apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configuration
  namespace: ingress-nginx
data:
  enable-vts-status: "true"
  log-format-upstream: '{"time":"$time_iso8601","remote_addr":"$remote_addr","x-forwarded-for":"$http_x_forwarded_for","request_id":"$req_id","remote_user":"$remote_user","bytes_sent":"$bytes_sent","request_time":"$request_time","status":"$status","vhost":"$host","request_proto":"$server_protocol","path":"$uri","request_query":"$args","request_length":"$request_length","duration":"$request_time","method":"$request_method","pid":"$pid","request":"$request","apptime":"$upstream_response_time","appstat":"$upstream_status","appreq":"$upstream_addr"}'
