apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: krakend
  name: krakend
spec:
  type: ClusterIP
  ports:
    - name: "http"
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    io.kompose.service: krakend
