apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: voting-service
  name: voting-service
spec:
  type: ClusterIP
  ports:
    - name: "http"
      port: 8082
      targetPort: 8082
      protocol: TCP
  selector:
    io.kompose.service: voting-service
