apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  type: LoadBalancer
  ports:
    - name: "http"
      port: 3000
      targetPort: 80
    - name: "https"
      port: 3001
      targetPort: 443
  selector:
    app: web  # This should match the labels used in your deployment
