apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  type: LoadBalancer
  loadBalancerIP: 4.182.99.127
  ports:
    - name: "http"
      port: 3000
      targetPort: 80
      protocol: TCP
    - name: "https"
      port: 3001
      targetPort: 443
      protocol: TCP
  selector:
    app: web 
