apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: voting
  name: voting
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: voting
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: voting
    spec:
      containers:
        - env:
            - name: KAFKA_BOOTSTRAP_SERVER
              valueFrom:
                configMapKeyRef:
                  key: KAFKA_BOOTSTRAP_SERVER
                  name: voting-env
          image: voting-service:latest
          name: voting
          ports:
            - containerPort: 8082
              protocol: TCP
      restartPolicy: Always
