apiVersion: v1
kind: Service
metadata:
  name: game-service
spec:
  type: LoadBalancer
  ports:
  - port: 6000
    targetPort: 6000
    protocol: TCP
  selector:
    app: game-service

---

apiVersion: v1
kind: Service
metadata:
  name: voting-service
spec:
  type: LoadBalancer
  ports:
  - port: 6000
    targetPort: 6000
    protocol: TCP
  selector:
    app: voting-service

---

apiVersion: v1
kind: Service
metadata:
  name: kafka-headless
  labels:
    app: kafka
spec:
  ports:
  - port: 9092
    name: client
  clusterIP: None
  selector:
    app: kafka

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-pvc-new
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi 

---

apiVersion: v1
kind: Service
metadata:
  name: angular-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: angular-app

