apiVersion: 1

datasources:
- name: influx
  type: influxdb
  access: proxy
  url: http://influxdb:8086
  database: krakend
  user: admin
  password: admin
  isDefault: true
  jsonData:
    httpMode: POST
