apiVersion: 1

datasources:
-  access: 'proxy'
   editable: true
   is_default: true
   name: 'influx'
   org_id: 1
   type: 'influxdb'
   url: '$INFLUXDB_HOST:$INFLUXDB_PORT'
   version: 1
   user: $INFLUXDB_USER
   password: $INFLUXDB_USER_PASSWORD
   database: krakend
