# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go Build and Dockerize

on:
  push:
    branches:
      - develop
    paths:
      - 'services/game/**'
  pull_request:
    branches:
      - main
    paths:
      - 'services/game/**'

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22.2'

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build the game service
        run: |
          cd services/game
          go build

      - name: Run tests
        run: |
          cd services/game
          go test ./...

  dockerize:
    name: Build and Push Docker image
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        run: |
          cd services/game
          docker build -t timojw/game-service:latest .
          docker push timojw/game-service:latest
